export const REQUEST_POPULAR_LIST = 'REQUEST_POPULAR_LIST';
export const RECEIVE_POPULAR_LIST_SUCCESS = 'RECEIVE_POPULAR_LIST_SUCCESS';
export const REQUEST_POPULAR_LIST_ERROR = 'REQUEST_POPULAR_LIST_ERROR';

export const SET_SELECTED_MOVIE = 'SET_SELECTED_MOVIE';
