export const REQUEST_MOVIES = 'REQUEST_MOVIES';
export const RECEIVE_MOVIES_SUCCESS = 'RECEIVE_MOVIES_SUCCESS';
export const REQUEST_MOVIES_ERROR = 'REQUEST_MOVIES_ERROR';

export const SET_SELECTED_MOVIE = 'SET_SELECTED_MOVIE';
