export const REQUEST_MOVIES = 'REQUEST_MOVIES';
export const RECEIVE_MOVIES_SUCCESS = 'RECEIVE_MOVIES_SUCCESS';
export const REQUEST_MOVIES_ERROR = 'REQUEST_MOVIES_ERROR';

export const REQUEST_MOVIE = 'REQUEST_MOVIE';
export const RECEIVE_MOVIE_SUCCESS = 'RECEIVE_MOVIE_SUCCESS';
export const REQUEST_MOVIE_ERROR = 'REQUEST_MOVIE_ERROR';

export const SET_SELECTED_MOVIE = 'SET_SELECTED_MOVIE';
